version: "3.8"

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aiagent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 010921
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cv-agent-network

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:010921@postgres:5432/aiagent
      SECRET_KEY: cv-agent-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      API_KEY: 9589ca16aa2844de6975809fbac3891ef2a105eadcde6f56e044c60b6b774ec4
      DIFY_API_URL: http://47.93.166.93/v1/chat-messages
      DIFY_API_KEY_PARSE: app-vUxIgRioYdHMLHNXthPohBBY
      DIFY_API_KEY_REWRITE: app-NSMi2PZtYBCE9ITWSMPH7kml
      DIFY_API_KEY_EXPAND: app-WHKgL6UEpETSTjx1BkINhLlW
      DIFY_API_KEY_CONTRACT: app-TKSk1t6qRkCTFfPtwuyRbOuT
      DIFY_API_KEY_PROCESS_TEXT: app-yJ7LozBBr8NGN3e1Qi9YleAQ
      DIFY_API_KEY_PERSONAL_STATEMENT: app-0MxV1MnP63vkOhL8RhM2uL33
      DIFY_API_KEY_RECOMMENDATION: app-rdL3VKcnhQaKYkSPXXfRnXih
      DIFY_API_KEY_PROMPT_BASED: app-wXht7rntyPhIPrcvnshpJ3ba
    ports:
      - "8700:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - cv-agent-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cv-agent-network:
    driver: bridge