version: '3.8'

services:
  backend:
    build: .  
    container_name: cv_agent_backend
    ports:
      - "8699:8699"  
    env_file:
      - ./.env  
    depends_on:
      - db  


  db:
    image: postgres:15-alpine 
    container_name: cv_agent_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env 
    ports:
      - "5432:5432" 